### ISSUE TITLE
switch links to homepage, show name on hover

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-semantic-linkbacks#112]
thanks so much again for facepiles! i'm excited!

i'll start to file requests. i'm agreeable on details, if they're opt in or opt out, etc.

my first request is an option to tweak the rendering, at least for likes and reposts, which don't usually have meaningful content. i'd like them to show the person's name or username on hover, and to link to their homepage or silo profile (ie `h-card u-url`) instead of the like permalink.

you'd just need to change the `href` in the outermost `<a>` and add `title`, e.g. from this:

```html
<a class="u-url" href="https://aaronparecki.com/2017/09/12/14/">
```

to this:

```html
<a class="u-url" title="Aaron Parecki" href="https://aaronparecki.com/">
```

**Comment by chrisaldrich** [comment]
Nota bene: Folks using facepiles with JetPack's Gravatar Hovercards will likely have issues in how facepiled mentions, likes, etc. display (ie they'll be hovercards instead of hover text and/or links to the originals). Ideally there should also be some UI to handle and/or mention this directly.

Brief instructions for those having issues will need to turn off hovercards:
[Gravatar Hovercards — Jetpack for WordPress](https://jetpack.com/support/gravatar-hovercards/)
Go to Settings -> Discussion.
Scroll down to the Avatar section.
You'll see a checkbox for “Gravatar Hovercards,” this will disable hovercards on your blog.

**Comment by dshanske** [comment]
I wonder if someone can get hovercard support in.

**Comment by snarfed** [comment]
i may start working on some of the facepile issues i filed, starting with this one. let me know if you've already started any of them. (one good way is by accepting/assigning.)

**Comment by dshanske** [comment]
I have not. I am still on another project and may not rotate back till it is done.
