### ISSUE TITLE
Excerpt Uses Post Format

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#19]
The excerpt uses Post Format. Which means if you don't use Post Format, all excerpts will use "Article"

I would want to use Post Kinds, but there is no easy way to change just the format.

**Comment by dshanske** [comment]
The Add to filters could be a fix for the problem, yes. I discovered I couldn't regenerate the text without the raw data.

**Comment by pfefferle** [comment]
after having a deeper look at this, I think we don't need any filter and I could remove it... just use the `comment_text` with a lower priority (so that it's called after this one) or remove the filters completely in your code: `remove_filter('comment_text', array('SemanticLinkbacksPlugin', 'comment_text_add_cite'), 11);`

**Comment by dshanske** [comment]
That one I can't argue with. Although I might suggest putting a remark about that around line 44 in the file.
