### ISSUE TITLE
Facepile for webmention does not link to source

### ISSUE THREAD

**Issue by metbril** [pfefferle/wordpress-semantic-linkbacks#208]
For testing purposes I created a new post that links to another of my own posts. This creates a new comment, through webmention I guess. When I approve it, it only shows the / my icon in a facepile with the link to my homepage. And not to the post that linked to my site. There is not way (from the blog itself, the admin page has the info) for me or my readers, to click a link and read the post that mentioned me.

I would therefor like to see and suggest that the icon in the facepile wil link back to the original post and not to the homepage of the author.

Example post:

https://robertvanbregt.nl/2018/09/04/mijn-internetsnelheid-in-2018/

links to

https://robertvanbregt.nl/2003/12/02/snelheid-adsl-wordt-opnieuw-verhoogd/

Discussions started in the Slack / IRC channel.

https://github.com/pfefferle/wordpress-semantic-linkbacks/commit/6c0386ae3299ae3e5c41c22d7d2e739a03cc9d3b#diff-f81f3dff36bf04b7a070d642c858e883

Reverts fix for #112?

cc @snarfed @sknebel

**Comment by metbril** [comment]
Well, for me personally , i would like to have some control over what is displayed for mentions (as for post kinds). Without having to build a custom theme. I won’t mind an excerpt but really like to be able to click to the source post. If someone writes a lengthy article and mentions me, I think I want to fully read it. Mys Florida I wouldn’t require the excerpt. It is visual clutter on my page. The face pile will do most of the time.

**Comment by snarfed** [comment]
one workaround you can try now is switching mentions from facepile to full display on the webmention settings page:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/778068/45056736-99d7f100-b048-11e8-9f66-5546fabcb564.png">

**Comment by chrisaldrich** [comment]
Here's a good example: <a href="http://v.hierofalco.net/2018/08/23/weird-indieweb-idea-of-the-day-guestbooks/" rel="noopener" target="_blank">http://v.hierofalco.net/2018/08/23/weird-indieweb-idea-of-the-day-guestbooks/</a>
There's a mention from https://ramblinggit.com/ in the comments, but it's incredibly difficult to find that mention or what it contains, because there isn't a linked URL on the avatar that goes to ramblinggit.com's (Brad Enslen's) content. In this particular case, it's probably the most important piece of content on the page because the post itself is about a theoretical idea or "blue sky", while the mention itself actually puts the theoretical idea into actual use and provides a great example. Sadly as it stands this value is completely hidden because of the UI. In some sense hiding the mention is also potentially contributing to unnecessary context collapse within hierofalco's post's comments and lessens the value of the mention itself.

While I appreciate the UX/UI desire to limit the amount of data displayed in one's comment section since it is rarely, if ever, used, there's a lot of value in the bi-directionality of webmentions and how they're displayed. I've [suggested before](https://alistapart.com/article/webmentions-enabling-better-communication-on-the-internet#section6) that newspapers, magazines and journalism sites (not to mention academics, researchers, and government sites) might benefit from the verifiable/audit-able links from their material to the reads, likes, favorites, and even listens (in the case of podcasts). If the comments sections simply have an avatar and a homepage link to the original, some of this (admittedly) marginal value is then lost. What about when Webmention is more common? Sites could simply display avatars and homepage links without actually linking to the original location of the webmention. They might do this to imply an endorsement(s) when none exists and the viewer is left with the difficult task of attempting manual verification.

I do love the fact that one can facepile these reactions, but why not simply have the facepile of avatars with URLs that direct to the original reaction? To me these should ideally have a title attribute that is the sending account's name wrapped with the URL of the original webmention URL itself. While these are seemingly "throwaways" for likes/favorites, I often personally post "reads" and "listens" that also have notes or commentary that I use for my own purpose and thus don't send them as explicit replies. If the facepiles for reads & listens are avatars that link back to the original then the site's admin as well as others can choose (or not) to click through to the original. Perhaps the site administrator prefers to display those as replies, then they have the option in the interface to change the semantic linkback type from the simple response to a more "featured" response. (I've <a href="https://boffosocko.com/2017/10/06/using-facepiles-in-comments-for-wordpress-with-webmentions-and-semantic-linkbacks/#Turning%20mentions%20into%20comments%20for%20native%20display" rel="noopener" target="_blank">documented an example of this before</a>.)

The issue becomes even more apparent in the case of "mentions" which are currently simply avatars with a homepage. There's a much higher likelihood that there's some valuable content (compared to a like certainly) behind this mention (though it still isn't a specific reply). Readers of comment sections are much more likely to be interested in them and the potential conversation hiding behind them. As things stand currently, it's a difficult and very manual thing to attempt to track down. In these cases, one should ideally be able to individually toggle facepile/not facepile for each mention depending on the content. If shown as a comment, then, yes, having the ability to show the whole thing, or an excerpted version, could be useful/desirable. If the mention is facepiled, it should be done as the others with an avatar and a wrapped URL to the mentioning content and an appropriate title (either the Identity/name of the sending site, the article title, or both if available). 

For facepiled posts (and especially mentions) I'd much rather see something along the lines of: 
`<a title="Brad Enslen" href="https://ramblinggit.com/2018/08/new-guestbook/"><img src="https://secure.gravatar.com/avatar/0ce8b2c406e423f114e39fd4d128c31d?s=100&amp;r=pg&amp;d=mm" width="100" height="100"/></a>`
(with the appropriate microformats markup, of course.)

As an example, what happens in the future when a _New York Times_ article has webmentions that get hundreds or thousands of webmentions? Having everything be facepiled would be incredibly useful for quick display, but being able to individually go follow the conversations in situ would be wildly valuable as well. The newspaper could also then choose to show/hide specific replies or mentions in a much more moderated fashion to better encourage civil discourse. In the case where a bad actor/publisher attempts to "game" the system by simply showing thousands of likes/favorites/reads, what is to prevent them from cheating by showing as many as they like as "social proof" of their popularity when the only backtrack record is an avatar and a homepage without the actual verification of a thing on a site if someone chooses to audit the trail?

Perhaps even a step further in interesting UI for these semi-hidden mentions would be to do a full page preview (or hovercards) in a similar method for how WordPress handles hovercards for Gravatars or they way the hover functionality works for links at `/wp-admin/edit-comments.php`?

Going even farther from a reader's perspective, I could also see a case that while the site admin wants to slim down on the UI of all the different types of interactions for easy readability, perhaps the reader of a comments section might want to see all the raw mentions and details for each one and scroll through them? Perhaps it would be nice to add that option in the future? As things stand if a site facepiles even dozens of mentions, it's incredibly painful and undesirable to track their associated commentary down. What if there was UI for the reader to unpack all these (especially per reaction category as it's more likely one would want to do it for mentions, but not likes)?

(Originally posted at https://boffosocko.com/2018/09/04/reply-to-facepile-for-webmention-does-not-link-to-source/)

**Comment by dshanske** [comment]
I like hovercards in theory. Wonder if we can do some sort of option to show more info

**Comment by dshanske** [comment]
Maybe a few UI options

**Comment by snarfed** [comment]
bump. i'm still looking forward to this. thanks in advance!
