### ISSUE TITLE
Replaces regular comments on recent versions of Wordpress/Jetpack comments

### ISSUE THREAD

**Issue by mapkyca** [pfefferle/wordpress-semantic-linkbacks#221]
On 5.1.1 of Wordpress and 7.0.1 + of jetpack, regular comments are replaced with "xxxx mentioned this" in the comments display.

Actual comments remain unmodified, and editing the comment or viewing the comments in the moderation page shows the regular text.

Disabling the plugin brings back the correct comment text

**Comment by armingrewe** [comment]
Strange, as far as I can tell they show just fine on all three of my blogs.

**Comment by mapkyca** [comment]
Only just noticed it, so not sure how long it has been like that.

When I have time I'll try and gather some more information...

**Comment by pfefferle** [comment]
This is the expected behavior. Only replies will show up as comments. Mentions, likes, repost, ... will be shown in the short way, you mentioned. This is because mentions may not be a direct reply to your Blogpost, so it might confuse people to see an „out of context“ text in the comment section. If the link uses the correct `u-in-reply-to` markup, then it is a bug in the parser.

**Comment by armingrewe** [comment]
What might also help is deselecting mention and reply in the settings. I can't remember what the exact issue was, but deselecting them helped when I had an issue of some sort.
![image](https://user-images.githubusercontent.com/9156586/54709673-dd560080-4b3d-11e9-8bbe-5dc4afd69097.png)
