### ISSUE TITLE
Webmention facepiles do not display when Jetpack feature "Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment” is enabled.

### ISSUE THREAD

**Issue by khurtwilliams** [pfefferle/wordpress-semantic-linkbacks#222]
Webmention facepiles do not display when WordPress feature "**Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment**” is enabled.

To duplicate, enable " "Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment” in Jetpack.

Visit webpage with Webmention facepiles.

Jetpack setting:

![Screen Shot 2019-04-17 at 4 48 56 PM](https://user-images.githubusercontent.com/686971/56320249-b6d1b800-6131-11e9-822e-85b0f47ada1d.jpg)

Behaviour seen:

![Screen Shot 2019-04-17 at 4 49 23 PM](https://user-images.githubusercontent.com/686971/56320263-c18c4d00-6131-11e9-91ed-13935d316a3d.jpg)

When "Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment” is disabled in Jetpack. 

![Screen Shot 2019-04-17 at 4 48 02 PM](https://user-images.githubusercontent.com/686971/56320315-e254a280-6131-11e9-9e5a-f56350883873.jpg)

Webmention facepiles are displayed as expected.

![Screen Shot 2019-04-17 at 4 48 39 PM](https://user-images.githubusercontent.com/686971/56320342-f4364580-6131-11e9-9c16-bf25f350fafd.jpg)

**Comment by billbennettnz** [comment]
I also have this issue. 

For now I'm keeping the Jetpack feature switched off.

**Comment by khurtwilliams** [comment]
The regular readers of my blog complained when I disabled JetPack comments. I disabled this plugin instead.

**Comment by billbennettnz** [comment]
I've switched it off, but I think people can still leave comments. What they can't do is sign-in with Wordpress.com or social media accounts. I was about to say that "otherwise it works fine", but I haven't had a single new comment since I switched and there are usually a few a day, so perhaps they are disabled. Tons of webmentions though.

**Comment by ScootRay** [comment]
I have this issue also with the Twenty Twenty theme. Turning off Jetpack for comments solves this issue but I noticed there are less comments now since folks like using their Wordpress.com accounts to comment, etc. with just one click login. 

I'm wondering if there is a way to resolve this somehow with Jetpack comments on?

Thanks,
Ray

**Comment by lordmatt** [comment]
I found unchecking facepile for posts and pages let the mentions be comments and that seemed to work.
