### ISSUE TITLE
Invisible u-mention links leave large gaps on WordPress 

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-semantic-linkbacks#234]
When someone replies to a Tweet containing my blog post, the webmention includes hidden links:

![Screenshot_2019-12-24 Comments ‹ Terence Eden’s Blog — WordPress](https://user-images.githubusercontent.com/837136/71413871-13d02700-264c-11ea-9a8f-cd6c33e7fcf7.png)

The text of the comment is
```
<a href="http://edent.tel/" rel="nofollow ugc"></a>
<a href="https://shkspr.mobi/blog/"></a>
<a href="https://twitter.com/alistair" rel="nofollow ugc"></a>
<a href="https://twitter.com/edent" rel="nofollow ugc"></a>
```
Thanks the link from my bio, my home page, and the Twitter usernames the comment is replying to.

What is the purpose of those links? Can they be removed?

**Comment by dshanske** [comment]
They aren't coming from this plugin. Did you check the bridgy version of the tweet? If it is there it would have come over as part of the content

**Comment by edent** [comment]
Ah, yes. Seems to come from Bridgy - https://brid-gy.appspot.com/comment/twitter/edent/1209420474964496385/1209445040814272513

I'll go bug them :-)

**Comment by dshanske** [comment]
Reopening this issue as @edent explained in the Bridgy issue https://github.com/snarfed/bridgy/issues/903 that the problem is not the links, the problem is the formatting they generate. See the notations re whitespace conversion on the other issue.

Propose that we address this by stripping hidden links out of the content entirely. They are marked up as microformats, if we choose to use them for anything, we should parse the microformats, but strip this out of the content.

**Comment by snarfed** [comment]
thanks @dshanske! [as mentioned in IRC](https://chat.indieweb.org/wordpress/2019-12-24#t1577231097206500), i definitely recommend you collapse whitespace instead of special-casing and removing these links, since any other webmentions with similar non-meaningful line breaks or other whitespace will cause the same problem. otherwise sgtm!

**Comment by edent** [comment]
I hid it with this CSS

```
a:empty + br {
    display: none;
}
```
