### ISSUE TITLE
why not using the native comment_type?

### ISSUE THREAD

**Issue by petermolnar** [pfefferle/wordpress-semantic-linkbacks#55]
hi pfefferle,

May I ask why have you added the type as comment meta instead of using the comment_type field for this?

**Comment by pfefferle** [comment]
I don't want to lose the pingback/trackback/webmention informations... but perhaps you might convince me ;)

**Comment by pfefferle** [comment]
...and not every theme supports different comment types!

**Comment by dshanske** [comment]
We already lose it to a degree for replies which are turned into comments

**Comment by dshanske** [comment]
I have a proposal on this for replies. We have a compelling reason to start storing the webmention source in meta due the overloading of the comment_author_url field in the database. Wouldn't the presence of such a field be an indicator of this?

**Comment by dshanske** [comment]
I am only proposing a change to refine our handling of replies right now.

**Comment by pfefferle** [comment]
I am ok with the change, but we should provide a migration for older entries.

**Comment by raamdev** [comment]
I've been following this issue with interest and I'd love to help contribute. 

If I'm following correctly, the intention here is to update the plugin so that replies get a `comment_type` of `webmention`, is that correct? Right now replies get handled as regular comments by WordPress because WordPress forces any comments with a blank `comment_type`, such as replies, to be [treated as if `comment_type` was set to `comment`](https://github.com/WordPress/WordPress/blob/4.7.4/wp-includes/comment.php#L882-L883).

**Comment by dshanske** [comment]
I thought the intention was to make it so the comment type was set to what the Semantic Linkback type is set to. Replies would still be set as type '' or comment because that is what they are. But likes, etc would have that type set. Webmention would be the type for a 'generic' mention only.

**Comment by dshanske** [comment]
Being as we now have rendering support for different types independent of theme if needed, this is not as big an issue.

**Comment by dshanske** [comment]
This is being discussed as part of changing the data structure.

**Comment by dshanske** [comment]
Closing this as this is being explored in the webmention plugin.
