### ISSUE TITLE
Correct author url

### ISSUE THREAD

**Issue by lostfocus** [pfefferle/wordpress-semantic-linkbacks#99]
With one of the last updates the behaviour for `$comment->comment_author_url` changed. It used to be the value of the custom field `semantic_linkbacks_author_url` and now it is `webmention_source_url` - which makes things pretty ugly, especially for brid.gy links.

**Comment by dshanske** [comment]
Can you elaborate on this with examples? Author URL is supposed to reflect the URL of the author. Pingbacks and Trackbacks use the field for the source URL. The webmention plugin started storing it separately to move away from that and allow author URL to be used for authors again. The issue is that the support for that isn't laid out better in Semantic Linkbacks, I think

**Comment by armingrewe** [comment]
I think I can give you an example: [My post from today has a few FB/Twitter webmentions via bridgy](http://www.islay.org.uk/2017/07/04/evening-mood-at-port-ellen-marina-and-loch-leodamais-isle-of-islay/). If you click on an author name it [now takes you to an bridgy/appspot page like this](https://brid-gy.appspot.com/like/twitter/islayblog/882108264355332096/220077432), in the past this would have taken you to the FB/Twitter/G+ profile of the person. Via that page you can still get to the profile, but it's a bit ugly.

**Comment by lostfocus** [comment]
Okay, so it could be the webmention plugin? It [looks similar at my blog](https://lostfocus.de/2017/06/14405/) with the bridgy.appspot links.

**Comment by dshanske** [comment]
Either way, the text is dynamically generated, so we'll push a fix shortly.

**Comment by snarfed** [comment]
noticed this recently on my own site. i'd love to get this bug fix. any chance you all could cut a new release soon? thanks in advance!
